# Generated by Django 6.0.3 on 2026-03-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('role_pt', models.CharField(max_length=200)),
                ('role_en', models.CharField(max_length=200)),
                ('bio_pt', models.TextField()),
                ('bio_en', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('seal_text_pt', models.CharField(default='Disponível para oportunidades · ', max_length=100)),
                ('seal_text_en', models.CharField(default='Open to opportunities · ', max_length=100)),
            ],
            options={
                'verbose_name': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('backend', 'Back-end'), ('frontend', 'Front-end'), ('infra', 'Infraestrutura / DB')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('title_pt', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('short_description_pt', models.TextField(max_length=300)),
                ('short_description_en', models.TextField(max_length=300)),
                ('case_study_pt', models.TextField()),
                ('case_study_en', models.TextField()),
                ('repo_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('skills', models.ManyToManyField(blank=True, to='portfolio.skill')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
