# Generated by Django 6.0.3 on 2026-09-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_singleton_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('backend', 'Back-end'), ('frontend', 'Front-end'), ('infra', 'Dados'), ('devops', 'DevOps e ferramentas'), ('testing', 'Testes'), ('ai', 'IA')], max_length=20),
        ),
    ]
