# Generated by Django 6.0.3 on 2026-10-03 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill_categories_from_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_en',
            field=models.FileField(blank=True, upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_pt',
            field=models.FileField(blank=True, upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
